### ISSUE TITLE
which value can be the approvalAddress in the lifi.approveToken?

### ISSUE THREAD

**Issue by leonidlewis** [lifinance/sdk#170]
When I attempt to bridge one token from Binance to another token, I encounter the token approval modal in Metamask.

Before calling the approveToken function, I must approve the token. Therefore, I've called the lifi.approveToken function.

However, I'm unsure which value should be added for the approvalAddress

_My dapp is connected with Binance network now and I've tried binance address._

signer: Signer;
    token: Token;
    **approvalAddress: string;** ------------------ which value?
    amount: string;
    infiniteApproval?: boolean;

**Comment by chybisov** [comment]
`approvalAddress` is the contract address to which you give access to your tokens, e.g., it can be LI.FI contract address if you want to execute a bridge/swap quote after the approval.

**Comment by leonidlewis** [comment]
Yes, I am going to run the following function after token approval
await lifi.executeRoute(signer, otherProps, {...switchChainHook});
please let me know the Li.Fi contract address.

**Comment by chybisov** [comment]
The `approveToken` function will be called for you if required as part of the `executeRoute`, so you don't need to run it separately. `approvalAddress` will also be provided automatically to the `approveToken` function from the route object that you need to pass to `executeRoute`

Here is a screenshot from /routes endpoint

<img width="760" alt="image" src="https://github.com/lifinance/sdk/assets/18644653/bc5d3825-9936-4baa-bd66-f25c6275d184">

**Comment by leonidlewis** [comment]
Thank you and I've got another error when I try to exchange the token from Binance to Polygon.
This function works on swap on the tokens in the same network.
```
const signBridgeTransaction = async () => {
    const signer = provider.getSigner(account);
    try {
      setIsTransactionLoading(true);
      const switchChainHook = async (requiredChainId: number) => {
        const ethereum = window.ethereum;
        if (typeof ethereum === 'undefined') return;
        await ethereum.request({
          method: 'wallet_switchEthereumChain',
          params: [{chainId: requiredChainId}],
        });
        const newProvider = new ethers.providers.Web3Provider(window.ethereum);
        return newProvider.getSigner();
      };

      await lifi.executeRoute(signer, transactionData, {...switchChainHook});

    } catch (error) {
      console.log(error);
    } 
  };
```
But I've got the following error when I click the run button.

```
TransactionError: Exchange rate has changed!
    at stepComparison (stepComparison.js:29:1)
    at async StepExecutionManager.execute (StepExecutionManager.js:93:1)
    at async StepExecutor.executeStep (StepExecutor.js:51:1)
    at async RouteExecutionManager.executeSteps (RouteExecutionManager.js:94:1)
    at async signBridgeTransaction (BridgeModal.tsx:177:1)
```

**Comment by chybisov** [comment]
> Thank you and I've got another error when I try to exchange the token from Binance to Polygon. This function works on swap on the tokens in the same network.
> 
> ```
> const signBridgeTransaction = async () => {
>     const signer = provider.getSigner(account);
>     try {
>       setIsTransactionLoading(true);
>       const switchChainHook = async (requiredChainId: number) => {
>         const ethereum = window.ethereum;
>         if (typeof ethereum === 'undefined') return;
>         await ethereum.request({
>           method: 'wallet_switchEthereumChain',
>           params: [{chainId: requiredChainId}],
>         });
>         const newProvider = new ethers.providers.Web3Provider(window.ethereum);
>         return newProvider.getSigner();
>       };
> 
>       await lifi.executeRoute(signer, transactionData, {...switchChainHook});
> 
>     } catch (error) {
>       console.log(error);
>     } 
>   };
> ```
> 
> But I've got the following error when I click the run button.
> 
> ```
> TransactionError: Exchange rate has changed!
>     at stepComparison (stepComparison.js:29:1)
>     at async StepExecutionManager.execute (StepExecutionManager.js:93:1)
>     at async StepExecutor.executeStep (StepExecutor.js:51:1)
>     at async RouteExecutionManager.executeSteps (RouteExecutionManager.js:94:1)
>     at async signBridgeTransaction (BridgeModal.tsx:177:1)
> ```

There is `acceptExchangeRateUpdateHook` which you should provide to handle these cases. If you want to accept a new rate, you can return `true` from it.

Your code should look something like

```ts
const signBridgeTransaction = async () => {
    const signer = provider.getSigner(account);
    try {
      setIsTransactionLoading(true);
      const switchChainHook = async (requiredChainId: number) => {
        const ethereum = window.ethereum;
        if (typeof ethereum === 'undefined') return;
        await ethereum.request({
          method: 'wallet_switchEthereumChain',
          params: [{chainId: requiredChainId}],
        });
        const newProvider = new ethers.providers.Web3Provider(window.ethereum);
        return newProvider.getSigner();
      };

      await lifi.executeRoute(signer, transactionData, {...switchChainHook, acceptExchangeRateUpdateHook: ({ oldToAmount, newToAmount, toToken }) => { 
        // your logic goes here or just return true
        return true
      }});

    } catch (error) {
      console.log(error);
    } 
  };
```
